# Generated by Django 4.2.6 on 2023-10-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="price",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
