# Generated by Django 4.2.6 on 2023-10-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0002_stock_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="price",
            field=models.IntegerField(null=True),
        ),
    ]
